"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = require("react");
nimport;
{
    useNavigate;
}
from;
'react-router-dom';
nimport;
type;
{
    Quote;
}
from;
'../types';
n;
nconst;
Dashboard = function () { n; var _a = (0, react_1.useState)([]), quotes = _a[0], setQuotes = _a[1]; n; var navigate = useNavigate(); n; n; (0, react_1.useEffect)(function () { n; var stored = localStorage.getItem('quotes'); n; if (stored) {
    n;
    setQuotes(JSON.parse(stored));
    n;
} n; }, []); n; n; var handleNewQuote = function () { n; navigate('/quote/new'); n; }; n; n; var handleEditQuote = function (id) { n; navigate("/quote/".concat(id)); n; }; n; n; return (); n; n < header; className = "bg-white shadow-sm border-b border-gray-200" > ; n < div; className = "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" > ; n < div; className = "flex justify-between items-center py-6 md:py-8" > ; n; n < h1; className = "text-3xl md:text-4xl font-bold text-gray-900" > MGA; Quote; Dashboard; h1 > ; n < p; className = "text-lg text-gray-600 mt-1" > Manage; your; commercial; insurance; quotes; p > ; n; div > ; n < button; n; onClick = { handleNewQuote: handleNewQuote }; n; className = "bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white font-bold py-3 px-6 rounded-xl shadow-lg focus:outline-none focus:ring-4 focus:ring-indigo-200 transition-all text-lg"; n > ; n + New; Quote; n; button > ; n; div > ; n; div > ; n; header > ; n; n < main; className = "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12" > ; n; {
    quotes.length === 0 ? () : ;
    n < div;
    className = "text-center py-24" > ;
    n < div;
    className = "mx-auto h-24 w-24 bg-gray-200 rounded-2xl flex items-center justify-center mb-6" > ;
    n < span;
    className = "text-3xl" > ;
    span > ;
    n;
    div > ;
    n < h2;
    className = "text-2xl font-bold text-gray-900 mb-4" > No;
    quotes;
    yet;
    h2 > ;
    n < p;
    className = "text-lg text-gray-600 mb-8" > Get;
    started;
    by;
    creating;
    your;
    first;
    commercial;
    property;
    or;
    GL;
    quote.;
    p > ;
    n < button;
    n;
    onClick = { handleNewQuote: handleNewQuote };
    n;
    className = "bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white font-bold py-3 px-8 rounded-xl shadow-lg focus:outline-none focus:ring-4 focus:ring-indigo-200 transition-all";
    n > ;
    n;
    Create;
    First;
    Quote;
    n;
    button > ;
    n;
    div > ;
    n;
    ();
    n;
    n < div;
    className = "mb-8" > ;
    n < h2;
    className = "text-2xl font-bold text-gray-900" > Recent;
    Quotes({ quotes: quotes, : .length });
    h2 > ;
    n;
    div > ;
    n < div;
    className = "bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden" > ;
    n < table;
    className = "min-w-full divide-y divide-gray-200" > ;
    n < thead;
    className = "bg-gray-50" > ;
    n;
    n < th;
    className = "px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" > Quote;
    ID;
    th > ;
    n < th;
    className = "px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" > Type;
    th > ;
    n < th;
    className = "px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" > Insured;
    th > ;
    n < th;
    className = "px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" > Total;
    Premium;
    th > ;
    n < th;
    className = "px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase tracking-wider" > Created;
    th > ;
    n;
    tr > ;
    n;
    thead > ;
    n < tbody;
    className = "bg-white divide-y divide-gray-200" > ;
    n;
    {
        quotes.map(function (quote) { return (); }, n < tr, n, key = { quote: quote, : .id }, n, onClick = {}(), handleEditQuote(quote.id));
    }
    n;
    className = "hover:bg-gray-50 cursor-pointer transition-colors h-16";
    n > ;
    n < td;
    className = "px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900" > { quote: quote, : .id.slice(0, 8) };
    td > ;
    n < td;
    className = "px-6 py-4 whitespace-nowrap" > ;
    n < span;
    className = {}(templateObject_1 || (templateObject_1 = __makeTemplateObject(["px-3 py-1 rounded-full text-xs font-bold ", ""], ["px-3 py-1 rounded-full text-xs font-bold ", ""])), );
    n;
    quote.type === 'property' ? 'bg-green-100 text-green-800' : ;
    n;
    quote.type === 'gl' ? 'bg-blue-100 text-blue-800' : ;
    n;
    'bg-purple-100 text-purple-800';
    n;
} "}>{\n                          quote.type.charAt(0).toUpperCase() + quote.type.slice(1)\n                        }</span>\n                      </td>\n                      <td className=\"px-6 py-4 text-sm text-gray-900\">{quote.insured.name}</td>\n                      <td className=\"px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900\">".concat(quote.totalPremium.toLocaleString(), "</td>\n                      <td className=\"px-6 py-4 whitespace-nowrap text-sm text-gray-500\">{new Date(quote.createdDate).toLocaleDateString()}</td>\n                    </tr>\n                  ))}\n                </tbody>\n              </table>\n            </div>\n          </>\n        )}\n      </main>\n    </>\n  );\n};\n\nexport default Dashboard;\n"); };
var templateObject_1;
